create table if not exists public.content_runs (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text not null,
  story_title text not null,
  story_summary text,
  score numeric,
  target text not null default 'arabic-short-form',
  status text not null default 'ready_for_review',
  blueprint jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists content_runs_created_at_idx
  on public.content_runs (created_at desc);

create index if not exists content_runs_status_idx
  on public.content_runs (status);
